# services:
#   - type: web
#     name: firedock
#     env: docker
#     dockerfilePath: ./Dockerfile
#     plan: free
#     envVars:
#       - key: PORT
#         value: 10000

services:
  - type: web
    name: firedock
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: PORT
        value: 5800
      - key: FF_OPEN_URL
        value: https://www.google.com
